### ISSUE TITLE
Documentation on usage in a pipeline

### ISSUE THREAD

**Issue by secana** [FabienLavocat/vsts-tasks#8]
Hi @FabienLavocat, I would like to use your plugin in an Azure YAML Pipeline but I don't know how. Could you provide an example on how to use the plugin with yaml?

**Comment by secana** [comment]
I got it working like this:

```yaml
  - task: PurgeAzureCDNEndpoint@2
    displayName: Purge CDN Cache
    inputs:
      ConnectedServiceNameARM: 'ARM Service Name'
      ConnectedServiceNameSelector: 'ConnectedServiceNameARM'
      ResourceGroupName: 'Resource Group Name'
      EndpointName: 'CDN Endpoint Name'
      ProfileName: 'CDN Profile Name'
```

Great plugin!
